# Generated by Django 5.0.4 on 2024-05-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=4)),
                ('Identifying_features', models.CharField(max_length=100)),
                ('Criminal_History', models.CharField(max_length=100)),
                ('Behavioral_Patterns', models.CharField(max_length=100)),
            ],
        ),
    ]
