# Generated by Django 5.0.4 on 2024-05-13 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camerafeatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspect',
            old_name='firstname',
            new_name='First_name',
        ),
        migrations.AddField(
            model_name='suspect',
            name='Image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
